[package]
name = "leptos_i18n_macro"
version = { workspace = true }
edition = "2021"
authors = ["Baptiste de Montangon"]
license = "MIT"
repository = "https://github.com/Baptistemontan/leptos_i18n"
description = "Macros for the leptos_i18n crate"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
serde = { version = "1", features = ["rc"] }
serde_json = "1"
proc-macro2 = "1"
quote = "1"
syn = "2.0"
toml = "0.7"

[features]
# default = ["supress_key_warnings"]
serde = []
debug_interpolations = []
nightly = []
supress_key_warnings = []

[package.metadata.cargo-all-features]
denylist = ["nightly"]
