[workspace]
resolver = "2"
members = [
    "leptos_i18n",
    "leptos_i18n_macro",
    "tests/common",
    "tests/namespaces",
    "tests/no_namespaces",
]
exclude = ["examples"]

[workspace.package]
version = "0.2.0-beta6"

[workspace.dependencies]
leptos_i18n = { path = "./leptos_i18n", version = "0.2.0-beta6" }
leptos_i18n_macro = { path = "./leptos_i18n_macro", version = "0.2.0-beta6" }
common = { path = "./tests/common" }
leptos = "0.5.0-rc3"
