name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Load cargo toolchain"
        uses: dtolnay/rust-toolchain@stable

      - name: "Test all features"
        run: |
          cargo install cargo-all-features
          cargo test-all-features

  compile_examples:
    name: Compile example ${{ matrix.examples }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        examples:
          [
            counter,
            counter_plurals,
            hello_world_actix,
            hello_world_axum,
            interpolation,
            namespaces,
            subkeys,
          ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Install wasm32-unknown-unknown"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          targets: "wasm32-unknown-unknown"

      - name: "Build exemple ${{ matrix.examples }}"
        working-directory: examples/${{ matrix.examples }}
        run: |
          cargo install cargo-leptos
          cargo leptos build

  test_suite:
    name: Compile test ${{ matrix.tests }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: [namespaces, no_namespaces]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Install wasm32-unknown-unknown"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          targets: "wasm32-unknown-unknown"

      - name: "Build test ${{ matrix.tests }}"
        working-directory: tests/${{ matrix.tests }}
        run: |
          cargo install cargo-leptos
          cargo leptos build
